# Автоматическая сборка 

name: CI

# Автосборка будет работать при отправке commit или pull request на всех ветках
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  # Разрешаем запуск вручную нажатием на кнопку в Actions tab
  workflow_dispatch:

# Выполнение рабочего процесса состоит из одного или нескольких заданий, которые могут выполняться последовательно или параллельно
jobs:
  # Задание сборки
  build:
    # Сборка будет на последней доступной версии Ubuntu
    runs-on: ubuntu-latest

    # Шаги представляют собой последовательность задач, которые будут выполняться как часть задания
    steps:
      - uses: actions/checkout@v3

      # Установка зависимостей
      - name: Установка зависимостей
        run: |
          sudo apt install python3 build-essential xorriso grub-pc-bin mtools zip doxygen
          wget -nv https://github.com/lordmilko/i686-elf-tools/releases/download/7.1.0/i686-elf-tools-linux.zip
          sudo unzip i686-elf-tools-linux.zip -d /usr/local
          rm i686-elf-tools-linux.zip

      # Запуск сборки
      - name: Сборка ядра
        run: |
          python scripts/build.py

      # Создание дистрибутива (ISO)
      - name: Создание дистрибутива (ISO) limine
        run: |
          git clone https://github.com/limine-bootloader/limine.git --branch=v3.0-branch-binary --depth=1
          make -C limine
          cp limine/limine-cd.bin isodir/
          cp limine/limine-cd-efi.bin isodir/
          cp limine/limine.sys isodir/
          xorriso -as mkisofs -b limine-cd.bin -no-emul-boot -boot-load-size 4 -boot-info-table --efi-boot limine-cd-efi.bin -efi-boot-part --efi-boot-image --protective-msdos-label isodir -o BelugaOS-limine.iso
          ./limine/limine-deploy BelugaOS-limine.iso